version: "3.9"

services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src
    ports: 
      - "8080:8000"
    container_name: vaipe_api_v01
    image: vaipe_api_v01:local 
    restart: always
